### ISSUE TITLE
Configuration webpage cant be opened

### ISSUE THREAD

**Issue by weaponmasterjax** [vcheckzen/LSP#2]
when installed successfully,the domain https://lsp.com get redirected to a petro company,not the config page.
Tested on Windows 11 with system doh enabled.

**Comment by vcheckzen** [comment]
LSP will take over dns resolution, disable doh both on system and browser.

**Comment by weaponmasterjax** [comment]
I did but no work.
Still redirecting to longsonpetro.com

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月28日 21:55
收件人: ***@***.***>
抄送: Bill ***@***.***>; ***@***.***>
主题: Re: [vcheckzen/LSP] Configuration webpage cant be opened (Issue #2)


LSP will take over dns resolution, disable doh both on system and browser.

―

**Comment by vcheckzen** [comment]
Set your system ipv4 dns to 127.0.0.1 if not set up automatically.

**Comment by weaponmasterjax** [comment]
It seems that lsp’s dns resolution is down.
I got a dns bad secure config in browser when the dns is forced to localhost

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月28日 22:14
收件人: ***@***.***>
抄送: Bill ***@***.***>; ***@***.***>
主题: Re: [vcheckzen/LSP] Configuration webpage cant be opened (Issue #2)


Set your system ipv4 dns to 127.0.0.1 if not set up automatically.

―

**Comment by vcheckzen** [comment]
no problem with me, join in the discussion group to give more feedback
